### PR TITLE
Change november to december

### PR DESCRIPTION
**Pull request by mrdrogdrog**
### Description
This PR changes the history entry for november and adds a history entry for december. November is changed to "release candidate" and december is about the release.

### Steps

- [x] Added changes
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc.github.io/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### CODE REVIEW

**Review by ErikMichelson — APPROVED** [review]

**Review by davidmehren — APPROVED** [review]

**Comment by DerMolly** [comment]
Do we really want to add the RC to the history? I'm not against it per se, but I'm curious if this seems necessary…

**Comment by mrdrogdrog** [comment]
I don't want to rewrite the history by saying "this didn't happen in November but will in December". We released something in November. But it was a rc.

**Comment by davidmehren** [comment]
Well, now you mention it, I would simply change "November" to "December" and not clutter the timeline with release candidates.

**Comment by mrdrogdrog** [comment]
I removed november

**Review by DerMolly — APPROVED** [review]

**Review by ErikMichelson — APPROVED** [review]

**Pull request merged**
