### PR TITLE
added team

### PR DESCRIPTION
**Pull request by DerMolly**
This PR adds a page (linked from the footer) that shows who works actively on HedgeDoc.

### CODE REVIEW

**Comment by ErikMichelson** [comment]
Is this ready to review? I don't see any PR description...

**Comment by DerMolly** [comment]
It is. I just forget to add one…

**Comment by mrdrogdrog** [comment]
Are there any hidden figures we want to add? Right now we have only the core devs. What about the cli or container contributors?

**Comment by SISheogorath** [comment]
First of all, can we pull the avatars at build time? And then: If we fetch stuff anyway, maybe we can use the output of the [contributors API](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#get-all-contributor-commit-activity) of our repositories to generate an automated contributor list?

As you might see here, this should not be called from the frontend due to GitHub rate-limits and the list generation simply being slow: 
https://api.github.com/repos/hedgedoc/hedgedoc/stats/contributors

**Comment by mrdrogdrog** [comment]
Why should we pull them at build time?

**Comment by SISheogorath** [comment]
It makes the website more self-contained and reduces calls to external sources.

**Comment by DerMolly** [comment]
I'm not sure this is a good idea as we would need to trigger periodically rebuilds to be even remotely up to date with either the avatars or the list of contributors. We could however link to the github conributers page (https://github.com/hedgedoc/hedgedoc/graphs/contributors) even if that's not really representative of all contributors (especially in the future).

**Comment by ErikMichelson** [comment]
Although automation is great in many places for keeping things up to date, I wouldn't implement such things for this.
We should keep in mind that with adding that complexity to the page (or it's render process) we make us dependant from GitHub's API and reduce the maintailability of such a team-page drastically.
In my opinion this is an example for overengineering a simple solution with energy that could be put more into version 1.7 or 2.0.

**Review by ErikMichelson — APPROVED** [review]

**Comment by DerMolly** [comment]
Is everybody satisfied with their designated functions?
image

**Review by mrdrogdrog — APPROVED** [review]

**Review by ErikMichelson — APPROVED** [review]

**Review by SISheogorath — APPROVED** [review]

**Review by pirate — APPROVED** [review]

**Review by InnayTool — APPROVED** [review]

**Review by davidmehren — APPROVED** [review]

**Review by ericgaspar — APPROVED** [review]

**Comment by DerMolly** [comment]
I just added @hugopeixoto with the function of 'Container' as they are now part of the organization…

**Review by hugopeixoto — APPROVED** [review]

**Pull request merged**
