### PR TITLE
Fix typo in SVG

### PR DESCRIPTION
**Pull request by Cadair**
I have no idea if editing this in place is the best thing or if this is generated from somewhere else, but there is what I assume is a typo in "The community wants to keeptheir code and keep the APGLv3 license.", it should be "AGPLv3"?

### CODE REVIEW

**Comment by mrdrogdrog** [comment]
@SISheogorath 
@ErikMichelson 
@ccoenen

**Comment by mrdrogdrog** [comment]
Yes, editing the svg inplace is right. It's a quick solution. We plan to replace it soon.

**Comment by DerMolly** [comment]
Could you elaborate why you think it should be AGPLv2? Because the License we use is AGPLv3…

**Comment by Cadair** [comment]
Oh sorry that's a typo I meant 3, the issue is the ordering of the letters in the acronym.

**Comment by Cadair** [comment]
For clarity the relevant part of the diff is:

image

**Comment by mrdrogdrog** [comment]
Ohhhhh..... We focused so much on the 2, that we missed the letters 😅. Okay that makes sense.

**Review by mrdrogdrog — APPROVED** [review]

**Review by ErikMichelson — APPROVED** [review]

**Review by DerMolly — APPROVED** [review]

**Comment by mrdrogdrog** [comment]
Thanks ❤️ @Cadair

**Comment by Cadair** [comment]
Sorry for the confusion 🙈

**Comment by mrdrogdrog** [comment]
Everything's okay. Without your hint we wouldn't have noticed that misspell 😅

**Pull request merged**
